name: .NET Core

on:
  push:
    branches: [ add-entity-framework ]
  pull_request:
    branches: [ add-entity-framework ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.0
    - name: Install dependencies
      run: dotnet restore --project .\CoachBot.API\CoachBot.API.csproj
    - name: Build
      run: dotnet build --project .\CoachBot.API\CoachBot.API.csproj --configuration Release --no-restore
